### ISSUE TITLE
Package is broken, downloaded files are no longer hosted at the paths hard-coded in the script

### ISSUE THREAD

**Issue by jacoblee93** [nomic-ai/gpt4all-ts#26]
A community member is trying to add GPT4All support to LangChainJS, but the models are no longer hosted at the paths in the SDK: https://github.com/hwchase17/langchainjs/pull/1204

The ideal solution would be to bundle/download the model into the `node_modules` folder on installation and bump it with new version releases - would this be possible? That way there's no reliance on updating a user's home directory.

**Comment by lujstn** [comment]
Just submitted a PR that fixes the file location in the short term. Agreed a discussion is probably needed re bundling the binary ^
