### ISSUE TITLE
Root readme.md says import from "gpt4all-ts" but should be "gpt4all"

### ISSUE THREAD

**Issue by dstults** [nomic-ai/gpt4all-ts#8]
The instructions say this:
```
import { GPT4All } from 'gpt4all-ts';
```

But after running `npm install gpt4all` the module files are inside `gpt4all`.
Link: https://www.npmjs.com/package/gpt4all?activeTab=code

Thus the readme code should probably be updated to say this:
```
import { GPT4All } from 'gpt4all';
```

**Comment by dstults** [comment]
Looks like there's a PR already to fix this: https://github.com/nomic-ai/gpt4all-ts/pull/6

**Comment by yourbuddyconner** [comment]
Thanks for reporting!
